name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Removi o cache temporariamente para garantir uma instalação limpa
          
      - name: Install Dependencies
        run: |
          # O comando 'npm ci' é melhor para servidores, pois ignora a pasta node_modules local
          # e instala exatamente o que está no package-lock.json para o Linux
          npm install --platform=linux --arch=x64 sharp
          npm install

      - name: Generate Icons and Splash
        run: |
          # Agora o Sharp estará instalado corretamente para o Linux
          npx capacitor-assets generate --android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk